name: waste_tracker
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.7.0
  intl: ^0.18.0
  shared_preferences: ^2.0.15
  cloud_firestore: ^4.4.3
  firebase_storage: ^11.0.14
  path: ^1.8.1
  path_provider: ^2.0.11
  image_picker: ^0.8.6+3
  cupertino_icons: ^1.0.2
  cached_network_image: ^3.2.3
  location: ^4.2.0
  test: ^1.20.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Cuprum
      fonts:
        - asset: assets/fonts/Cuprum.ttf
    - family: Lora
      fonts:
        - asset: assets/fonts/Lora.ttf
        - asset: assets/fonts/Lora_Italic.ttf
          style: italic
